### ISSUE TITLE
Remove the need for the alpha version env var

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/release-toolkit#277]
When we've adopted the use of the version.properties file in all our clients we'll no longer need the `HAS_ALPHA_VERSION` env var. We should go ahead and remove this. 

https://github.com/wordpress-mobile/release-toolkit/pull/258#discussion_r651901418

**Comment by AliSoftware** [comment]
👍

~Update: that env var should be replaced by passing the name of the flavor used for alpha builds as a parameter (`ConfigItem`) to each fastlane action needing it~

Update of the Update: this has since been refactored as part of version `2.0.0`. The `HAS_ALPHA_VERSION` is still present in some places and will still need to get removed (in favor of using a `ConfigItem` when appropriate), but it was reverted to be evaluated to set (=`1`) or not, not the flavor name anymore as introduced in `1.3.x`)
