### ISSUE TITLE
Issue with new localization action

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/release-toolkit#315]
@AliSoftware during the WordPress iOS 18.8 code freeze, I encountered an issue. Unfortunately, I run out of time today so dumping this here without any research is the best I could do 😅 

```
/Users/gio/Developer/a8c/wpios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[0;31;49m[!] Shell command exited with exit status 66 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
genstrings: error: failed to read input file WordPress/dirname /Users/gio/Developer/a8c/wpios/DerivedData/WordPress/Build/Products/Secrets/Secrets.swift
\e[0m
```

I experienced this on my MacBook Pro, where I do most of my work. When I run `code_freeze` from my M1 MacMini, it worked fine 🤔

**Comment by AliSoftware** [comment]
I'll take a look today (having `pod install` issues… seems that's my turn now 😅 ) but that seems very strange that `genstrings` would try to parse `WordPress/dirname` (where does that odd name come from?).

As for the script trying to parse things in your `DerivedData`, I think it's fair (for now†) to exclude `DerivedData` from the files being parsed, by adding it to the `exclude` parameter of the call site in the `Fastfile`.

_(†) We might need to revisit that later in case for example we consider using e.g. Sourcery for some of our code and the templates we use end up generating code somewhere in `DerivedData/…/DerivedSources/…` that could contain `NSLocalizedString`… but we're not there yet._

All that being said, what seems even stranger to me is that the wording of the error message suggests that it's not about 2 different files (`dirname` and `Secrets.swift`) where it fails to parse each… but rather like if it was trying to parse a single file with a path of `WordPress/dirname /Users/gio/…` with a space in the middle 🤔

**Comment by AliSoftware** [comment]
Ok I just checked out `release/18.8` on WPiOS repo, and tried to run `fl generate_strings_file_for_glotpress` and didn't manage to reproduce the error.

While I do have a `DerivedData` folder with a `Secrets.swift` file in my local working copy still:
```
✓ $ find DerivedData -name Secrets.swift

DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/WordPress Internal/BuildProductsPath/Secrets/Secrets.swift

✓ $ fl generate_strings_file_for_glotpress

[…snip…]

[18:42:58]: ▸ Pod installation complete! There are 78 dependencies from the Podfile and 97 total pods installed.
[18:42:58]: -------------------------------------------------
[18:42:58]: --- Step: ios_generate_strings_file_from_code ---
[18:42:58]: -------------------------------------------------
[18:43:01]: -------------------------------------------------
[18:43:01]: --- Step: ios_generate_strings_file_from_code ---
[18:43:01]: -------------------------------------------------
[18:43:01]: -------------------------------------------------
[18:43:01]: --- Step: ios_generate_strings_file_from_code ---
[18:43:01]: -------------------------------------------------
[18:43:01]: ------------------------
[18:43:01]: --- Step: git_commit ---
[18:43:01]: ------------------------
[18:43:01]: $ git status WordPress/Resources/en.lproj WordPress/WordPressTodayWidget/Base.lproj WordPress/WordPressShareExtension/Base.lproj --porcelain
[18:43:01]: Nothing to commit, working tree clean ✅.

[…snip…]

[18:43:01]: fastlane.tools finished successfully 🎉
```

Besides, despite me having that `DerivedData` folder there, when I run fastlane in `--verbose` mode to see the whole `genstrings` command, there is no such path passed to my `genstrings` invocation. And that makes sense, because the globs that are given at call site in the `fastlane/Fastfile` are: `ios_generate_strings_file_from_code(paths: ['WordPress/', 'Pods/WordPress*/', 'Pods/WPMediaPicker/', 'WordPressShared/WordPressShared/', 'Pods/Gutenberg/'], …)` so that would not even consider `DerivedData`.

@mokagio All this makes me think that what my glob it actually did match in your local working copy is actually a buggy folder named `WordPress/dirname /Users/…` that maybe you accidentally created during past tests you did on working on some scripts in your Mac…

I'd be curious how you ended up with that and what that is (is it a symlink which ends up pointing to `/`, it might not even be a proper path but instead maybe those `/` are part of the buggy file name (and not folder separators) if those were created by a script that messed things up… which means that you probably have such a strange pseudo-`Secrets.swift` file that might not be a "regular text" (in the UNIX sense of things) but rather a symlink? Or maybe it's a file that does not have the `r` chmod permission…?

---

In any case, that's something to fix on your local working copy by removing that buggy file likely leftover from you previously toying with other scripts.

Things you could try:
 - Checking if you do have a `WordPress/dirname` file left over somewhere in your local working copy, and what that is
 - Try re-running the lane but with verbose mode, aka `be fastlane --verbose generate_strings_file_for_glotpress`. This should generate one hell of a log for the full command line (in cyan) but then you could ⌘F in that big a** log if there are instances of `DerivedData` and/or `WordPress/dirname` and how they appear (I'm betting as one file with the space char escaped, not as 2 files)

**Comment by mokagio** [comment]
@AliSoftware thank you for doing all the investigation for me 😄 😅 

> All this makes me think that what my glob it actually did match in your local working copy is actually a buggy folder named `WordPress/dirname /Users/…` that maybe you accidentally created during past tests you did on working on some scripts in your Mac…

That is indeed correct! 🤯 

I happen to have a `WordPress/dirname` and `WordPress/basename` folder on the machine I use the most:

```
➜ tree WordPress/dirname\ /
WordPress/dirname\ /
└── Users
    └── gio
        └── Developer
            └── a8c
                └── wpios
                    └── DerivedData
                        └── WordPress
                            └── Build
                                └── Products
                                    └── Secrets
                                        └── Secrets.swift
```

I have no idea how I ended up with those. Given the name and the content, I'm guessing it was during the work I did extracting the secrets from the local repo. I guess I never noticed them because of `DerivedData` being the only subfolder and that folder name being ignored.
