### ISSUE TITLE
iOS Localization Linting can't check duplicate keys in XML-formatted strings files

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/release-toolkit#405]
It crashes with `Invalid character '<' found on line 1, col 1`.

We probably need to detect the XML format and process it differently.

**Comment by AliSoftware** [comment]
Note that if the strings file is in XML format, checking for duplicate keys likely doesn't really make sense, since those XML strings are typically generated by us via `plutil`, which should (iinm) take care of keys deduplication (the same way reading a `.strings` file in a Dictionary / `Hash` does, by the property that keys are unique in a dictionary)

So the solution at call site is easy: just [disable duplicate keys detection](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_lint_localizations.rb#L175) for XML files.

On WPiOS, we don't lint XML files at all, because:
 - `Localizable.strings` files are not turned into XML — we keep the files downloaded from GlotPress unchanged
 - Other, manually-maintained files like `InfoPlist.strings` or `MyIntentTarget.strings`, which are generated as XML because they come from our tooling extracting the keys that had previously been merged in `Localizable.strings` to put them back in those `InfoPlist.strings` et al., are not linted, because those don't use placeholders anyway (the `InfoPlist.strings` and `MyIntentTarget.strings` files are not used in code via `String(format: NSLocalizedString(…), …)`, but are used by the system or an `.intentdefinition` directly instead, and thus iinm those usually don't have `%@/%d/…` placeholders to begin with, so nothing to lint there.

That being said, we could still consider adding a check in the action to detect if the file is in XML format (we [already have a helper for that](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/lib/fastlane/plugin/wpmreleasetoolkit/helper/ios/ios_l10n_helper.rb#L21)) and print either a `UI.warning` or a `UI.user_error!` when we detect XML files, to mention that linting those is not supported (and kinda doesn't make sense, given my assumptions/explanations above) and trying to lint those is considered a config error from the call site?

**Comment by leandroalonso** [comment]
I just experience that while releasing a new beta of Pocket Casts iOS. 😅

@mokagio recently changed the way we download the strings and the output is XML files. As @AliSoftware commented, adding `check_duplicate_keys: false` on the lint call fixes the issue.

Not a big deal but I think skipping duplicate keys detection (with a message) might be better than failing?

**Comment by AliSoftware** [comment]
> Not a big deal but I think skipping duplicate keys detection (with a message) might be better than failing?

@leandroalonso Great idea! This should be fixed by https://github.com/wordpress-mobile/release-toolkit/pull/418 🙂
